### ISSUE TITLE
Kill or Change this repo

### ISSUE THREAD

**Issue by tylerhannan** [basho-labs/vagrant-riak-cluster#3]
I've used the repo, in it's present state, quite a bit for demos...

It came up at the O'reilly strata conf that someone had tried to use it to test Riak, it had failed, and they were annoyed...so I fixed it with the work I've been doing on a local fork.

My use case/implementation was a fairly specific one.  I would like to either remove this repo entirely...or replace with the work done by @hectcastro on https://github.com/hectcastro/vagrant-riak-cluster.  

The approach I've adopted is messy, doesn't scale, and really only designed to solve my specific trade-show/meetup demo scenario.

**Comment by mjbrender** [comment]
Killing this fork and re-forking from the much better state of @hectcastro's version.
